//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValentineEntities : DbContext
    {
        public ValentineEntities()
            : base("name=ValentineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Concepto> T_Concepto { get; set; }
        public virtual DbSet<T_Cuenta> T_Cuenta { get; set; }
        public virtual DbSet<T_Cuota> T_Cuota { get; set; }
        public virtual DbSet<T_Inversor> T_Inversor { get; set; }
        public virtual DbSet<T_Oferta> T_Oferta { get; set; }
        public virtual DbSet<T_Pago> T_Pago { get; set; }
        public virtual DbSet<T_PagoDetalle> T_PagoDetalle { get; set; }
        public virtual DbSet<T_Parametro> T_Parametro { get; set; }
        public virtual DbSet<T_Perfil> T_Perfil { get; set; }
        public virtual DbSet<T_Prestamo> T_Prestamo { get; set; }
        public virtual DbSet<T_Prestatario> T_Prestatario { get; set; }
        public virtual DbSet<T_Solicitante> T_Solicitante { get; set; }
        public virtual DbSet<T_SolicitudAfiliacion> T_SolicitudAfiliacion { get; set; }
        public virtual DbSet<T_SolicitudCredito> T_SolicitudCredito { get; set; }
        public virtual DbSet<T_Subasata> T_Subasata { get; set; }
        public virtual DbSet<T_Transaccion> T_Transaccion { get; set; }
        public virtual DbSet<T_Usuario> T_Usuario { get; set; }
    }
}
