//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Archivo
    {
        public int codigoArchivo { get; set; }
        public int codigoSolCredito { get; set; }
        public string rutaArchivo { get; set; }
    }
}
