//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMultiplica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cuota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Cuota()
        {
            this.T_Pago = new HashSet<T_Pago>();
            this.T_PagoDetalle = new HashSet<T_PagoDetalle>();
            this.T_Transaccion = new HashSet<T_Transaccion>();
        }
    
        public string codigoCuota { get; set; }
        public string numeroCuota { get; set; }
        public short fechaPago { get; set; }
        public double monto { get; set; }
        public short fechaVencimiento { get; set; }
        public string codigoPrestamo { get; set; }
    
        public virtual T_Prestamo T_Prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Pago> T_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PagoDetalle> T_PagoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Transaccion> T_Transaccion { get; set; }
    }
}
