//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMultiplica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Cuenta()
        {
            this.T_Transaccion = new HashSet<T_Transaccion>();
        }
    
        public int codigoCuenta { get; set; }
        public short fechaApertura { get; set; }
        public string moneda { get; set; }
        public double saldo { get; set; }
        public int codigoInversor { get; set; }
        public int codigoPrestatario { get; set; }
    
        public virtual T_Inversor T_Inversor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Transaccion> T_Transaccion { get; set; }
    }
}
