//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pago
    {
        public int codigoPago { get; set; }
        public short fechaPago { get; set; }
        public short fechaProceso { get; set; }
        public double montoPagado { get; set; }
        public string tipoOperacion { get; set; }
        public string ctacteOrigen { get; set; }
        public bool fueProcesado { get; set; }
        public int numeroCuota { get; set; }
        public int codigoPrestamo { get; set; }
        public int codigoCuota { get; set; }
    
        public virtual T_Cuota T_Cuota { get; set; }
        public virtual T_PagoDetalle T_PagoDetalle { get; set; }
    }
}
