//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMultiplica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Pago
    {
        public string codigoPago { get; set; }
        public short fechaPago { get; set; }
        public short fechaProceso { get; set; }
        public double montoPagado { get; set; }
        public string tipoOperacion { get; set; }
        public string ctacteOrigen { get; set; }
        public bool fueProcesado { get; set; }
        public int numeroCuota { get; set; }
        public string codigoPrestamo { get; set; }
        public string codigoCuota { get; set; }
    
        public virtual T_Cuota T_Cuota { get; set; }
        public virtual T_PagoDetalle T_PagoDetalle { get; set; }
    }
}
