//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMultiplica.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PagoDetalle
    {
        public double montoCuota { get; set; }
        public Nullable<int> codigoPrestamo { get; set; }
        public Nullable<int> codigoCuota { get; set; }
        public int codigoPago { get; set; }
        public int codigoConcepto { get; set; }
    
        public virtual T_Concepto T_Concepto { get; set; }
        public virtual T_Cuota T_Cuota { get; set; }
        public virtual T_Pago T_Pago { get; set; }
    }
}
