//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Prestatario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Prestatario()
        {
            this.T_Inversor = new HashSet<T_Inversor>();
            this.T_Prestamo = new HashSet<T_Prestamo>();
            this.T_SolicitudCredito = new HashSet<T_SolicitudCredito>();
        }
    
        public int codigoPrestatario { get; set; }
        public string nombresPrestatario { get; set; }
        public string apellidosPrestatario { get; set; }
        public short fechaNacimiento { get; set; }
        public int tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public short ultimaEvaluacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Inversor> T_Inversor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Prestamo> T_Prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SolicitudCredito> T_SolicitudCredito { get; set; }
    }
}
