//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Solicitante
    {
        public int codigoSolicitante { get; set; }
        public string numeroDni { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombres { get; set; }
        public string docSustentatorio { get; set; }
        public string lugarNacimiento { get; set; }
        public string fechaNacimiento { get; set; }
        public string nombrePadre { get; set; }
        public string nombreMadre { get; set; }
        public double estatura { get; set; }
        public string sexo { get; set; }
        public string estadoCivil { get; set; }
        public string gradoInstruccion { get; set; }
        public short fechaEmision { get; set; }
        public string restricciones { get; set; }
        public short fechaInscripcion { get; set; }
        public string constanciaVotacion { get; set; }
        public string ubigeoDomicilio { get; set; }
        public short fechaConsulta { get; set; }
    }
}
