//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SolicitudCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SolicitudCredito()
        {
            this.T_Prestamo = new HashSet<T_Prestamo>();
            this.T_Subasata = new HashSet<T_Subasata>();
        }
    
        public int codigoSolCredito { get; set; }
        public string nombreSolicitante { get; set; }
        public string apellidoPaternoSolicitante { get; set; }
        public string apellidoMaternoSolicitante { get; set; }
        public Nullable<int> tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string digitoVerificacion { get; set; }
        public string correoElectronico { get; set; }
        public string numeroCelular { get; set; }
        public string fechaNacimiento { get; set; }
        public Nullable<int> genero { get; set; }
        public Nullable<int> gradoInstruccion { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public Nullable<double> ingresoMensual { get; set; }
        public string direccionSolicitante { get; set; }
        public Nullable<int> distritoSolicitante { get; set; }
        public Nullable<int> provinciaSolicitante { get; set; }
        public Nullable<int> dptoSolicitante { get; set; }
        public Nullable<int> paisSolicitante { get; set; }
        public Nullable<int> areaActividad { get; set; }
        public Nullable<int> ocupacion { get; set; }
        public string lugarTrabajo { get; set; }
        public string destinoCredito { get; set; }
        public string nombreConyuge { get; set; }
        public string apellidoPaternoConyuge { get; set; }
        public string apellidoMaternoConyuge { get; set; }
        public Nullable<int> tipoDocumentoConyuge { get; set; }
        public string numeroDocConyuge { get; set; }
        public Nullable<double> montoSolicitado { get; set; }
        public string detalleMotivo { get; set; }
        public Nullable<bool> esPEP { get; set; }
        public string cargoPEP { get; set; }
        public Nullable<int> tipoCuenta { get; set; }
        public Nullable<int> nombreEntidad { get; set; }
        public string codigoInterbancario { get; set; }
        public string seguroDesgravamen { get; set; }
        public Nullable<int> plazoPrestamo { get; set; }
        public string dniValido { get; set; }
        public string ingresoAcorde { get; set; }
        public string sobreEndeudado { get; set; }
        public string conyugeAcorde { get; set; }
        public string creditoActual { get; set; }
        public string historialCrediticioAcorde { get; set; }
        public string perfilSolicitante { get; set; }
        public Nullable<double> teaAsignada { get; set; }
        public string puntuacionBuro { get; set; }
        public string resultadoEvaluacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> codigoPrestatario { get; set; }
        public string codigoPostal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Prestamo> T_Prestamo { get; set; }
        public virtual T_Prestatario T_Prestatario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Subasata> T_Subasata { get; set; }
    }
}
