//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valentine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Transaccion
    {
        public int codigoTransaccion { get; set; }
        public short fecha { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public double importe { get; set; }
        public double balance { get; set; }
        public Nullable<int> codigoPrestamo { get; set; }
        public Nullable<int> codigoCuota { get; set; }
        public int codigoCuenta { get; set; }
    
        public virtual T_Cuenta T_Cuenta { get; set; }
        public virtual T_Cuota T_Cuota { get; set; }
    }
}
